# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0002_expendituretype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListExpenditure',
            fields=[
                ('id_list_expenditure', models.IntegerField(primary_key=True, serialize=False)),
                ('detail', models.TextField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=1, max_length=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id_order_type', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=1, max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='listexpenditure',
            name='id_order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.OrderType'),
        ),
        migrations.AddField(
            model_name='listexpenditure',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
