# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20180508_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='listexpenditure',
            name='number',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
